server:
  port: 8770
spring:
  application:
    name: vets-service
  cloud:
    config:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true