server:
  port: 8765
spring:
  application:
    name: zuul-server
zuul:
  prefix: /api
  routes:
    owner:
      path: /owner/**
      serviceId: owner-service
    vet:
      path: /vets/**
      serviceId: vets-service